## Runtime patch generated by R/prepare_length_selectivity_sensitivity_steps.R.
## Sensitivity: LBS surface75 2 + LL+IDX N4
## Change: 4-node selectivity with surface young-zero 2 and adult/index monotone

edit_matrix <- rbind(
  c(-999L, 61L, 4L),
  c(-12L, 75L, 2L),
  c(-13L, 75L, 2L),
  c(-16L, 75L, 2L),
  c(-17L, 75L, 2L),
  c(-18L, 75L, 2L),
  c(-19L, 75L, 2L),
  c(-20L, 75L, 2L),
  c(-21L, 75L, 2L),
  c(-22L, 75L, 2L),
  c(-23L, 75L, 2L),
  c(-24L, 75L, 2L),
  c(-25L, 75L, 2L),
  c(-26L, 75L, 2L),
  c(-27L, 75L, 2L),
  c(-28L, 75L, 2L),
  c(-1L, 16L, 1L),
  c(-2L, 16L, 1L),
  c(-3L, 16L, 1L),
  c(-4L, 16L, 1L),
  c(-5L, 16L, 1L),
  c(-6L, 16L, 1L),
  c(-7L, 16L, 1L),
  c(-8L, 16L, 1L),
  c(-9L, 16L, 1L),
  c(-10L, 16L, 1L),
  c(-11L, 16L, 1L),
  c(-29L, 16L, 1L),
  c(-30L, 16L, 1L),
  c(-31L, 16L, 1L),
  c(-32L, 16L, 1L),
  c(-33L, 16L, 1L)
)

doitall <- file.path(model_dir, "doitall.sh")
if (!file.exists(doitall)) stop("Missing doitall.sh in ", model_dir, call. = FALSE)
lines <- readLines(doitall, warn = FALSE)
marker <- "# Turn on weighted spline for calculating maturity at age"
insert_at <- match(marker, lines)
if (is.na(insert_at)) stop("Could not find selectivity insertion marker in doitall.sh", call. = FALSE)
format_switch <- function(row) sprintf("  %6d %d %d", row[[1]], row[[2]], row[[3]])
switches <- apply(edit_matrix, 1, format_switch)
block <- c(
  "",
  "# Length-based selectivity sensitivity: LBS surface75 2 + LL+IDX N4",
  "# 4-node selectivity with surface young-zero 2 and adult/index monotone",
  switches
)
lines <- append(lines, block, after = insert_at - 1L)
writeLines(lines, doitall, useBytes = TRUE)
message("Applied length-based selectivity sensitivity: LBS surface75 2 + LL+IDX N4")
