## Runtime patch generated by R/prepare_length_selectivity_sensitivity_steps.R.
## Sensitivity: LBS DOM/PL dome25 N4
## Change: 4-node length-based selectivity with DOM/PL cutoffs set to 25

edit_matrix <- rbind(
  c(-999L, 61L, 4L),
  c(-16L, 3L, 25L),
  c(-21L, 3L, 25L),
  c(-22L, 3L, 25L),
  c(-23L, 3L, 25L),
  c(-24L, 3L, 25L)
)

doitall <- file.path(model_dir, "doitall.sh")
if (!file.exists(doitall)) stop("Missing doitall.sh in ", model_dir, call. = FALSE)
lines <- readLines(doitall, warn = FALSE)
marker <- "# Turn on weighted spline for calculating maturity at age"
insert_at <- match(marker, lines)
if (is.na(insert_at)) stop("Could not find selectivity insertion marker in doitall.sh", call. = FALSE)
format_switch <- function(row) sprintf("  %6d %d %d", row[[1]], row[[2]], row[[3]])
switches <- apply(edit_matrix, 1, format_switch)
block <- c(
  "",
  "# Length-based selectivity sensitivity: LBS DOM/PL dome25 N4",
  "# 4-node length-based selectivity with DOM/PL cutoffs set to 25",
  switches
)
lines <- append(lines, block, after = insert_at - 1L)
writeLines(lines, doitall, useBytes = TRUE)
message("Applied length-based selectivity sensitivity: LBS DOM/PL dome25 N4")
