## Runtime patch generated by R/prepare_length_selectivity_sensitivity_steps.R.
## Sensitivity: LBS no low dome + IDX N4
## Change: 4-node length-based selectivity with low dome constraints removed and index monotone

edit_matrix <- rbind(
  c(-999L, 61L, 4L),
  c(-16L, 16L, 0L),
  c(-17L, 16L, 0L),
  c(-18L, 16L, 0L),
  c(-21L, 16L, 0L),
  c(-22L, 16L, 0L),
  c(-23L, 16L, 0L),
  c(-24L, 16L, 0L),
  c(-16L, 3L, 37L),
  c(-17L, 3L, 37L),
  c(-18L, 3L, 37L),
  c(-21L, 3L, 37L),
  c(-22L, 3L, 37L),
  c(-23L, 3L, 37L),
  c(-24L, 3L, 37L),
  c(-29L, 16L, 1L),
  c(-30L, 16L, 1L),
  c(-31L, 16L, 1L),
  c(-32L, 16L, 1L),
  c(-33L, 16L, 1L)
)

doitall <- file.path(model_dir, "doitall.sh")
if (!file.exists(doitall)) stop("Missing doitall.sh in ", model_dir, call. = FALSE)
lines <- readLines(doitall, warn = FALSE)
marker <- "# Turn on weighted spline for calculating maturity at age"
insert_at <- match(marker, lines)
if (is.na(insert_at)) stop("Could not find selectivity insertion marker in doitall.sh", call. = FALSE)
format_switch <- function(row) sprintf("  %6d %d %d", row[[1]], row[[2]], row[[3]])
switches <- apply(edit_matrix, 1, format_switch)
block <- c(
  "",
  "# Length-based selectivity sensitivity: LBS no low dome + IDX N4",
  "# 4-node length-based selectivity with low dome constraints removed and index monotone",
  switches
)
lines <- append(lines, block, after = insert_at - 1L)
writeLines(lines, doitall, useBytes = TRUE)
message("Applied length-based selectivity sensitivity: LBS no low dome + IDX N4")
