## Runtime patch generated by R/prepare_length_selectivity_sensitivity_steps.R.
## Sensitivity: LBS IDXmono N7
## Change: 7-node length-based selectivity with non-decreasing index selectivity

edit_matrix <- rbind(
  c(-999L, 61L, 7L),
  c(-29L, 16L, 1L),
  c(-30L, 16L, 1L),
  c(-31L, 16L, 1L),
  c(-32L, 16L, 1L),
  c(-33L, 16L, 1L)
)

doitall <- file.path(model_dir, "doitall.sh")
if (!file.exists(doitall)) stop("Missing doitall.sh in ", model_dir, call. = FALSE)
lines <- readLines(doitall, warn = FALSE)
marker <- "# Turn on weighted spline for calculating maturity at age"
insert_at <- match(marker, lines)
if (is.na(insert_at)) stop("Could not find selectivity insertion marker in doitall.sh", call. = FALSE)
format_switch <- function(row) sprintf("  %6d %d %d", row[[1]], row[[2]], row[[3]])
switches <- apply(edit_matrix, 1, format_switch)
block <- c(
  "",
  "# Length-based selectivity sensitivity: LBS IDXmono N7",
  "# 7-node length-based selectivity with non-decreasing index selectivity",
  switches
)
lines <- append(lines, block, after = insert_at - 1L)
writeLines(lines, doitall, useBytes = TRUE)
message("Applied length-based selectivity sensitivity: LBS IDXmono N7")
