## Runtime patch generated by R/prepare_length_selectivity_sensitivity_steps.R.
## Sensitivity: LBS PS dome20 N4
## Change: 4-node length-based selectivity with main purse-seine dome cutoffs set to 20

edit_matrix <- rbind(
  c(-999L, 61L, 4L),
  c(-19L, 3L, 20L),
  c(-20L, 3L, 20L),
  c(-25L, 3L, 20L),
  c(-26L, 3L, 20L),
  c(-27L, 3L, 20L),
  c(-28L, 3L, 20L)
)

doitall <- file.path(model_dir, "doitall.sh")
if (!file.exists(doitall)) stop("Missing doitall.sh in ", model_dir, call. = FALSE)
lines <- readLines(doitall, warn = FALSE)
marker <- "# Turn on weighted spline for calculating maturity at age"
insert_at <- match(marker, lines)
if (is.na(insert_at)) stop("Could not find selectivity insertion marker in doitall.sh", call. = FALSE)
format_switch <- function(row) sprintf("  %6d %d %d", row[[1]], row[[2]], row[[3]])
switches <- apply(edit_matrix, 1, format_switch)
block <- c(
  "",
  "# Length-based selectivity sensitivity: LBS PS dome20 N4",
  "# 4-node length-based selectivity with main purse-seine dome cutoffs set to 20",
  switches
)
lines <- append(lines, block, after = insert_at - 1L)
writeLines(lines, doitall, useBytes = TRUE)
message("Applied length-based selectivity sensitivity: LBS PS dome20 N4")
