## Create lightweight step folders for the length-based selectivity sensitivity grid.

source("R/length_selectivity_sensitivity_rows.R")

format_edit <- function(edit) {
  sprintf("  c(%dL, %dL, %dL)", edit[["scope"]], edit[["flag"]], edit[["value"]])
}

patch_contents <- function(spec) {
  edit_lines <- vapply(spec$edits, format_edit, character(1))
  edit_block <- paste(edit_lines, collapse = ",\n")
  c(
    "## Runtime patch generated by R/prepare_length_selectivity_sensitivity_steps.R.",
    sprintf("## Sensitivity: %s", spec$label),
    sprintf("## Change: %s", spec$change),
    "",
    "edit_matrix <- rbind(",
    edit_block,
    ")",
    "",
    "doitall <- file.path(model_dir, \"doitall.sh\")",
    "if (!file.exists(doitall)) stop(\"Missing doitall.sh in \", model_dir, call. = FALSE)",
    "lines <- readLines(doitall, warn = FALSE)",
    "marker <- \"# Turn on weighted spline for calculating maturity at age\"",
    "insert_at <- match(marker, lines)",
    "if (is.na(insert_at)) stop(\"Could not find selectivity insertion marker in doitall.sh\", call. = FALSE)",
    "format_switch <- function(row) sprintf(\"  %6d %d %d\", row[[1]], row[[2]], row[[3]])",
    "switches <- apply(edit_matrix, 1, format_switch)",
    "block <- c(",
    "  \"\",",
    sprintf("  \"# Length-based selectivity sensitivity: %s\",", spec$label),
    sprintf("  \"# %s\",", spec$change),
    "  switches",
    ")",
    "lines <- append(lines, block, after = insert_at - 1L)",
    "writeLines(lines, doitall, useBytes = TRUE)",
    sprintf("message(\"Applied length-based selectivity sensitivity: %s\")", spec$label)
  )
}

readme_contents <- function(spec) {
  rows <- vapply(spec$edits, function(edit) {
    sprintf("| `%d %d %d` |", edit[["scope"]], edit[["flag"]], edit[["value"]])
  }, character(1))
  c(
    sprintf("# %s", spec$step_id),
    "",
    sprintf("Runtime sensitivity patch for `%s`.", spec$label),
    "",
    sprintf("- Change: %s", spec$change),
    sprintf("- Notes: %s", spec$notes),
    "- Source model: `steps/12-LengthBasedSel/model`",
    "- Patch insertion point: immediately before the maturity weighted-spline line in PHASE 1.",
    "",
    "## Switches",
    "",
    "| Appended MFCL switch |",
    "| --- |",
    rows,
    "",
    "The appended switches are placed after the base Step 12 selectivity block, so MFCL's sequential option parsing applies these as the final values."
  )
}

specs <- length_selectivity_sensitivity_specs()
for (spec in specs) {
  step_dir <- file.path("steps", spec$step_id)
  dir.create(step_dir, recursive = TRUE, showWarnings = FALSE)
  writeLines(readme_contents(spec), file.path(step_dir, "README.md"), useBytes = TRUE)
  writeLines(patch_contents(spec), file.path(step_dir, "patch.R"), useBytes = TRUE)
}

message("Prepared ", length(specs), " length-based selectivity sensitivity step folders.")
