## Runtime patch generated by R/prepare_length_selectivity_sensitivity_steps.R.
## Sensitivity: LBS LL recent mono N4
## Change: 4-node non-decreasing selectivity for later longline fishery groups

edit_matrix <- rbind(
  c(-999L, 61L, 4L),
  c(-7L, 16L, 1L),
  c(-8L, 16L, 1L),
  c(-9L, 16L, 1L),
  c(-10L, 16L, 1L),
  c(-11L, 16L, 1L)
)

doitall <- file.path(model_dir, "doitall.sh")
if (!file.exists(doitall)) stop("Missing doitall.sh in ", model_dir, call. = FALSE)
lines <- readLines(doitall, warn = FALSE)
marker <- "# Turn on weighted spline for calculating maturity at age"
insert_at <- match(marker, lines)
if (is.na(insert_at)) stop("Could not find selectivity insertion marker in doitall.sh", call. = FALSE)
format_switch <- function(row) sprintf("  %6d %d %d", row[[1]], row[[2]], row[[3]])
switches <- apply(edit_matrix, 1, format_switch)
block <- c(
  "",
  "# Length-based selectivity sensitivity: LBS LL recent mono N4",
  "# 4-node non-decreasing selectivity for later longline fishery groups",
  switches
)
lines <- append(lines, block, after = insert_at - 1L)
writeLines(lines, doitall, useBytes = TRUE)
message("Applied length-based selectivity sensitivity: LBS LL recent mono N4")
